# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Acılıs.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cam(object):
    def setupUi(self, Cam):
        Cam.setObjectName("Cam")
        Cam.resize(698, 496)
        Cam.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(Cam)
        self.label.setGeometry(QtCore.QRect(30, 30, 641, 431))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Cam)
        QtCore.QMetaObject.connectSlotsByName(Cam)

    def retranslateUi(self, Cam):
        _translate = QtCore.QCoreApplication.translate
        Cam.setWindowTitle(_translate("Cam", "HOSFACE"))
