# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Arama.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomePage(object):
    def setupUi(self, HomePage):
        HomePage.setObjectName("HomePage")
        HomePage.resize(789, 331)
        HomePage.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.LTc = QtWidgets.QLabel(HomePage)
        self.LTc.setGeometry(QtCore.QRect(20, 20, 751, 291))
        self.LTc.setMinimumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setItalic(False)
        self.LTc.setFont(font)
        self.LTc.setStyleSheet("Color: rgb(255, 255, 255)")
        self.LTc.setAlignment(QtCore.Qt.AlignCenter)
        self.LTc.setObjectName("LTc")
        self.pushButton = QtWidgets.QPushButton(HomePage)
        self.pushButton.setGeometry(QtCore.QRect(20, 260, 751, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(HomePage)
        QtCore.QMetaObject.connectSlotsByName(HomePage)

    def retranslateUi(self, HomePage):
        _translate = QtCore.QCoreApplication.translate
        HomePage.setWindowTitle(_translate("HomePage", "HOSFACE"))
        self.LTc.setText(_translate("HomePage", "Welcome To Hospital \n"
" Say The Word \"OPEN\" To Make An Appointment."))
