# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HastaArama.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HastaArama(object):
    def setupUi(self, HastaArama):
        HastaArama.setObjectName("HastaArama")
        HastaArama.resize(387, 226)
        HastaArama.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(0, 0, 0);")
        self.pushButton = QtWidgets.QPushButton(HastaArama)
        self.pushButton.setGeometry(QtCore.QRect(30, 160, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.LineTcGiris = QtWidgets.QLineEdit(HastaArama)
        self.LineTcGiris.setGeometry(QtCore.QRect(130, 100, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LineTcGiris.setFont(font)
        self.LineTcGiris.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.LineTcGiris.setStyleSheet(" background-color:rgb(255, 255, 255)")
        self.LineTcGiris.setInputMethodHints(QtCore.Qt.ImhNone)
        self.LineTcGiris.setText("")
        self.LineTcGiris.setMaxLength(11)
        self.LineTcGiris.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.LineTcGiris.setCursorPosition(0)
        self.LineTcGiris.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LineTcGiris.setDragEnabled(False)
        self.LineTcGiris.setReadOnly(False)
        self.LineTcGiris.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.LineTcGiris.setClearButtonEnabled(False)
        self.LineTcGiris.setObjectName("LineTcGiris")
        self.pushButton_2 = QtWidgets.QPushButton(HastaArama)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 100, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("alternate-background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.progressBar = QtWidgets.QProgressBar(HastaArama)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(30, 30, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.progressBar.setFont(font)
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.progressBar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.progressBar.setMaximum(10)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(HastaArama)
        QtCore.QMetaObject.connectSlotsByName(HastaArama)

    def retranslateUi(self, HastaArama):
        _translate = QtCore.QCoreApplication.translate
        HastaArama.setWindowTitle(_translate("HastaArama", "HOSFACE"))
        self.pushButton.setText(_translate("HastaArama", "Tc Identity Check"))
        self.LineTcGiris.setPlaceholderText(_translate("HastaArama", "Only Numbers"))
        self.pushButton_2.setText(_translate("HastaArama", "Tc"))
